[env:esp32-s3-n16r8]
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 1152000
board_build.f_cpu = 240000000L
board_build.partitions = max_app_8MB.csv

; board_build.psram_type = opi

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_SPRINTF_CUSTOM=1
    '-DLV_SPRINTF_INCLUDE="stdio.h"'
    -DUSER_SETUP_LOADED
    -DST7789_DRIVER
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=11
    -DTFT_MISO=-1
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=9
    -DTFT_RST=13
    -DTFT_BL=14
    -DSPI_FREQUENCY=27000000
    -DUSE_HSPI_PORT

lib_deps =
    lvgl/lvgl@^8.3.11
    bodmer/TFT_eSPI@^2.5.43

build_src_filter =
    +<*>
    +<../UI/components/*.c>
    +<../UI/fonts/*.c>
    +<../UI/images/*.c>
    +<../UI/screens/*.c>
    +<../UI/ui_helpers.c>
    -<../UI/ui.c>
