// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_setting4 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_forcedSwitch = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_forcedSwitch1 = NULL;
lv_obj_t * ui_return3 = NULL;
lv_obj_t * ui_Label38 = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting4 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_setting4, 230);
    lv_obj_set_height(ui_setting4, 30);
    lv_obj_set_x(ui_setting4, 5);
    lv_obj_set_y(ui_setting4, 5);
    lv_obj_clear_flag(ui_setting4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting4, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setting4, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setting4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_setting4);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "系统高级设置");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel17, 230);
    lv_obj_set_height(ui_Panel17, 160);
    lv_obj_set_x(ui_Panel17, 5);
    lv_obj_set_y(ui_Panel17, 40);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -47);
    lv_obj_set_y(ui_Label45, -60);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "电源强制关机");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forcedSwitch = lv_switch_create(ui_Panel17);
    lv_obj_set_width(ui_forcedSwitch, 50);
    lv_obj_set_height(ui_forcedSwitch, 25);
    lv_obj_set_x(ui_forcedSwitch, 56);
    lv_obj_set_y(ui_forcedSwitch, -60);
    lv_obj_set_align(ui_forcedSwitch, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -47);
    lv_obj_set_y(ui_Label1, -30);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "蜂鸣器开关");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forcedSwitch1 = lv_switch_create(ui_Panel17);
    lv_obj_set_width(ui_forcedSwitch1, 50);
    lv_obj_set_height(ui_forcedSwitch1, 25);
    lv_obj_set_x(ui_forcedSwitch1, 56);
    lv_obj_set_y(ui_forcedSwitch1, -30);
    lv_obj_set_align(ui_forcedSwitch1, LV_ALIGN_CENTER);

    ui_return3 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_return3, 230);
    lv_obj_set_height(ui_return3, 30);
    lv_obj_set_x(ui_return3, 5);
    lv_obj_set_y(ui_return3, 205);
    lv_obj_clear_flag(ui_return3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_return3, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_return3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_return3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_return3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_return3, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_return3, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label38 = lv_label_create(ui_return3);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "返回");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_setting4 = NULL;
    ui_Label29 = NULL;
    ui_Panel17 = NULL;
    ui_Label45 = NULL;
    ui_forcedSwitch = NULL;
    ui_Label1 = NULL;
    ui_forcedSwitch1 = NULL;
    ui_return3 = NULL;
    ui_Label38 = NULL;

}
