// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_setting3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_return2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_SSID;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_wifiIP;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_wifiTime;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_wifiState;
extern lv_obj_t * ui_openWifi;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_cleanWifi;
extern lv_obj_t * ui_Label27;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

