// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_inputVoltage = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_inputCurrent = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_inputPower = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_setting = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_fanSpeed = NULL;
lv_obj_t * ui_temp1 = NULL;
lv_obj_t * ui_PSON = NULL;
lv_obj_t * ui_runTime = NULL;
lv_obj_t * ui_PSONSwitch = NULL;
lv_obj_t * ui_deviceName = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_outputVoltage = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_outputCurrent = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_outputPower = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_effi = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 111);
    lv_obj_set_height(ui_Panel1, 150);
    lv_obj_set_x(ui_Panel1, 6);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xCBD5E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel7, 100);
    lv_obj_set_height(ui_Panel7, 45);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, -47);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xC53D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -10);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "输入电压");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inputVoltage = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_inputVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inputVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_inputVoltage, 0);
    lv_obj_set_y(ui_inputVoltage, 10);
    lv_obj_set_align(ui_inputVoltage, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_inputVoltage, "220.0V");
    lv_obj_set_style_text_color(ui_inputVoltage, lv_color_hex(0xFFF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inputVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inputVoltage, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel8, 100);
    lv_obj_set_height(ui_Panel8, 45);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x16A34A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -10);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "输入电流");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF6FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inputCurrent = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_inputCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inputCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_inputCurrent, 0);
    lv_obj_set_y(ui_inputCurrent, 10);
    lv_obj_set_align(ui_inputCurrent, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_inputCurrent, "0.000A");
    lv_obj_set_style_text_color(ui_inputCurrent, lv_color_hex(0xF6FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inputCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inputCurrent, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel9, 100);
    lv_obj_set_height(ui_Panel9, 45);
    lv_obj_set_x(ui_Panel9, 0);
    lv_obj_set_y(ui_Panel9, 47);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -10);
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label4, "输入功率");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inputPower = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_inputPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inputPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_inputPower, 0);
    lv_obj_set_y(ui_inputPower, 10);
    lv_obj_set_align(ui_inputPower, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_inputPower, "000.0W");
    lv_obj_set_style_text_color(ui_inputPower, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inputPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inputPower, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_546246141);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 32);
    lv_obj_set_y(ui_Image1, -97);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_setting, 111);
    lv_obj_set_height(ui_setting, 20);
    lv_obj_set_x(ui_setting, -6);
    lv_obj_set_y(ui_setting, 218);
    lv_obj_set_align(ui_setting, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setting, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_setting, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_setting, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label10 = lv_label_create(ui_setting);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "设置");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 126);
    lv_obj_set_height(ui_Panel4, 40);
    lv_obj_set_x(ui_Panel4, 6);
    lv_obj_set_y(ui_Panel4, 2);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, -10);
    lv_obj_set_y(ui_temp, -12);
    lv_label_set_text(ui_temp, "温度:0000");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fanSpeed = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_fanSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fanSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fanSpeed, -10);
    lv_obj_set_y(ui_fanSpeed, 5);
    lv_label_set_text(ui_fanSpeed, "风速:0000 Rpm");
    lv_obj_set_style_text_color(ui_fanSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fanSpeed, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp1, 70);
    lv_obj_set_y(ui_temp1, -12);
    lv_label_set_text(ui_temp1, "℃");
    lv_obj_set_style_text_color(ui_temp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp1, &ui_font_fuhao, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSON = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PSON, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PSON, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PSON, 13);
    lv_obj_set_y(ui_PSON, 220);
    lv_label_set_text(ui_PSON, "PSON");
    lv_obj_set_style_text_color(ui_PSON, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSON, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_runTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_runTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_runTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_runTime, 135);
    lv_obj_set_y(ui_runTime, 198);
    lv_label_set_text(ui_runTime, "00:00:00");
    lv_obj_set_style_text_color(ui_runTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_runTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_runTime, &ui_font_bold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSONSwitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_PSONSwitch, 40);
    lv_obj_set_height(ui_PSONSwitch, 18);
    lv_obj_set_x(ui_PSONSwitch, 70);
    lv_obj_set_y(ui_PSONSwitch, 220);

    ui_deviceName = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_deviceName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deviceName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deviceName, 85);
    lv_obj_set_y(ui_deviceName, -97);
    lv_obj_set_align(ui_deviceName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deviceName, "CSPS\nPower");
    lv_obj_set_style_text_color(ui_deviceName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deviceName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deviceName, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 111);
    lv_obj_set_height(ui_Panel3, 150);
    lv_obj_set_x(ui_Panel3, -6);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xCBD5E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel10, 100);
    lv_obj_set_height(ui_Panel10, 45);
    lv_obj_set_x(ui_Panel10, 0);
    lv_obj_set_y(ui_Panel10, -47);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xC53D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -10);
    lv_obj_set_align(ui_Label7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label7, "输出电压");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outputVoltage = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_outputVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outputVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outputVoltage, 0);
    lv_obj_set_y(ui_outputVoltage, 10);
    lv_obj_set_align(ui_outputVoltage, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_outputVoltage, "220.0V");
    lv_obj_set_style_text_color(ui_outputVoltage, lv_color_hex(0xFFF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outputVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outputVoltage, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel11, 100);
    lv_obj_set_height(ui_Panel11, 45);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x16A34A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -10);
    lv_obj_set_align(ui_Label8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label8, "输出电流");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xF6FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outputCurrent = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_outputCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outputCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outputCurrent, 0);
    lv_obj_set_y(ui_outputCurrent, 10);
    lv_obj_set_align(ui_outputCurrent, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_outputCurrent, "0.000A");
    lv_obj_set_style_text_color(ui_outputCurrent, lv_color_hex(0xF6FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outputCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outputCurrent, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel12, 100);
    lv_obj_set_height(ui_Panel12, 45);
    lv_obj_set_x(ui_Panel12, 0);
    lv_obj_set_y(ui_Panel12, 47);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -10);
    lv_obj_set_align(ui_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label9, "输出功率");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outputPower = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_outputPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outputPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outputPower, 0);
    lv_obj_set_y(ui_outputPower, 10);
    lv_obj_set_align(ui_outputPower, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_outputPower, "000.0W");
    lv_obj_set_style_text_color(ui_outputPower, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outputPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outputPower, &ui_font_bold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel13, 111);
    lv_obj_set_height(ui_Panel13, 22);
    lv_obj_set_x(ui_Panel13, 6);
    lv_obj_set_y(ui_Panel13, 197);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_effi = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_effi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_effi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_effi, -6);
    lv_obj_set_y(ui_effi, 1);
    lv_obj_set_align(ui_effi, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_effi, "效率:00.00%");
    lv_obj_set_style_text_color(ui_effi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_effi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_effi, &ui_font_bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel1 = NULL;
    ui_Panel7 = NULL;
    ui_Label6 = NULL;
    ui_inputVoltage = NULL;
    ui_Panel8 = NULL;
    ui_Label5 = NULL;
    ui_inputCurrent = NULL;
    ui_Panel9 = NULL;
    ui_Label4 = NULL;
    ui_inputPower = NULL;
    ui_Image1 = NULL;
    ui_setting = NULL;
    ui_Label10 = NULL;
    ui_Panel4 = NULL;
    ui_temp = NULL;
    ui_fanSpeed = NULL;
    ui_temp1 = NULL;
    ui_PSON = NULL;
    ui_runTime = NULL;
    ui_PSONSwitch = NULL;
    ui_deviceName = NULL;
    ui_Panel3 = NULL;
    ui_Panel10 = NULL;
    ui_Label7 = NULL;
    ui_outputVoltage = NULL;
    ui_Panel11 = NULL;
    ui_Label8 = NULL;
    ui_outputCurrent = NULL;
    ui_Panel12 = NULL;
    ui_Label9 = NULL;
    ui_outputPower = NULL;
    ui_Panel13 = NULL;
    ui_effi = NULL;

}
