// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_inputVoltage;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_inputCurrent;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_inputPower;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_tempBoard;
extern lv_obj_t * ui_fanSpeed;
extern lv_obj_t * ui_sheshidu1;
extern lv_obj_t * ui_PSON;
extern lv_obj_t * ui_runTime;
extern lv_obj_t * ui_PSONSwitch;
extern lv_obj_t * ui_deviceName;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_outputVoltage;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_outputCurrent;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_outputPower;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_effi;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_temp1;
extern lv_obj_t * ui_temp2;
extern lv_obj_t * ui_sheshidu2;
extern lv_obj_t * ui_sheshidu3;
extern lv_obj_t * ui_warning;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

