// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_setting2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_rom;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_wifiSetting;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_brightNess;
extern lv_obj_t * ui_systemSetting;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_powerSetting;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_screenReduce;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_screenAdd;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_return;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

