// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_546246141);    // assets/wifi-off-line.png
LV_IMG_DECLARE(ui_img_1533918671);    // assets/警告.png
LV_IMG_DECLARE(ui_img_808252844);    // assets/wifi-fill.png
LV_IMG_DECLARE(ui_img_1177623285);    // assets/系统.png
LV_IMG_DECLARE(ui_img_1259645767);    // assets/电源适配器.png
LV_IMG_DECLARE(ui_img_252039257);    // assets/亮度_o.png

// FONTS
LV_FONT_DECLARE(ui_font_bold16);
LV_FONT_DECLARE(ui_font_bold20);
LV_FONT_DECLARE(ui_font_bold24);
LV_FONT_DECLARE(ui_font_fuhao);
LV_FONT_DECLARE(ui_font_jetBrains24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
